### ISSUE TITLE
drag and drop storage directory specifications

### ISSUE THREAD

**Issue by MourIdri** [remy/html5demos#75]
Hi there, 
I saw this https://github.com/remy/html5demos/blob/master/demos/dnd-upload.html 
This is awesome !
However, I do not see where we could specify the directory were the files can be stored on local server. 

Thanks a lot for your script. I am a not good a Php and javascript either : ) . Using it with my raspberry..

**Comment by remy** [comment]
They're not stored, they're pushed into `/dev/null` - which means the dustbin.
